#
version: '3'

services:
  otc-backend:
    image: 'yvonnetest/otc-docker-backend-image:latest'
    build:
      context: .
    container_name: otc-backend
    depends_on:
      - postgres
      - rabbitmq
      - elasticsearch
      - pgadmin
    environment:
       #SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/otcDb
       SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
       SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
       SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8000:8000"
    networks:
      - otc-network

  postgres:
    container_name: postgres
    image: postgres
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       PGDATA: /data/postgres
    volumes: 
      - postgres:/data/postgres
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - otc-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes: 
      - pgadmin:/var/lib/pgadmin
    ports: 
      - "5050:80"
    networks:
      - otc-network

  frontend:
    container_name: otc-frontend
    image: 'yvonnetest/otc-vite-react-frontend-image:latest'
    ports:
      - "2000:2000"
    networks:
      - otc-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - otc-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - otc-network

volumes:
  postgres:
  pgadmin:

networks:
  otc-network:
    driver: bridge